import { access, readFile, writeFile } from "node:fs/promises";
import { constants } from "node:fs";
import path from "node:path";
import os from "node:os";
import { integrationBranchName, trustLeadApprovalsEnabled } from "./integration-policy.js";

export const CONFIG_FILE = "mission-control.config.md";
export const CONFIG_EXAMPLE_FILE = "mission-control.config.example.md";

export function expandHome(value) {
  if (!value || typeof value !== "string") return value;
  if (value === "~") return os.homedir();
  if (value.startsWith("~/")) return path.join(os.homedir(), value.slice(2));
  return value;
}

export async function fileExists(filePath) {
  try {
    await access(filePath, constants.F_OK);
    return true;
  } catch {
    return false;
  }
}

export function extractConfigJson(markdown) {
  const match = markdown.match(/```json mission-control-config\s*([\s\S]*?)```/);
  if (!match) {
    throw new Error("No fenced `json mission-control-config` block found.");
  }
  return JSON.parse(match[1]);
}

export function renderConfigMarkdown(config) {
  return `# Mission Control Local Configuration

This file was generated by \`mission-control setup\`.

Do not paste private keys, API tokens, passwords, customer data, or secrets into this file.

## Security Rules

- Mission Control verifies GitHub access; it does not store private keys.
- Keep this file local. It is ignored by Git.
- Keep secrets in each project's normal secret manager or environment files.

## Machine-Readable Config

\`\`\`json mission-control-config
${JSON.stringify(config, null, 2)}
\`\`\`
`;
}

export async function loadConfig(rootDir = process.cwd()) {
  const configPath = path.join(rootDir, CONFIG_FILE);
  if (!(await fileExists(configPath))) return null;
  const markdown = await readFile(configPath, "utf8");
  return extractConfigJson(markdown);
}

export async function writeConfig(config, rootDir = process.cwd()) {
  const configPath = path.join(rootDir, CONFIG_FILE);
  await writeFile(configPath, renderConfigMarkdown(config), "utf8");
  return configPath;
}

function hasOwnValue(item, key) {
  return Object.prototype.hasOwnProperty.call(item || {}, key);
}

function reviewPolicyFromConfig(rawProject = {}, defaults = {}) {
  const reviewPolicy = {
    ...(defaults.reviewPolicy || {}),
    ...(rawProject.reviewPolicy || {}),
  };
  if (
    !hasOwnValue(rawProject.reviewPolicy, "trustLeadApprovals")
    && !hasOwnValue(rawProject.reviewPolicy, "trustLeads")
    && hasOwnValue(rawProject, "trustLeadApprovals")
  ) {
    reviewPolicy.trustLeadApprovals = rawProject.trustLeadApprovals;
  }
  if (
    !hasOwnValue(rawProject.reviewPolicy, "integrationBranch")
    && !hasOwnValue(rawProject.reviewPolicy, "reviewBranch")
    && hasOwnValue(rawProject, "integrationBranch")
  ) {
    reviewPolicy.integrationBranch = rawProject.integrationBranch;
  }
  return reviewPolicy;
}

export function projectFromConfig(rawProject, defaults = {}) {
  const reviewPolicy = reviewPolicyFromConfig(rawProject, defaults);
  return {
    key: rawProject.key,
    name: rawProject.name,
    description: rawProject.description || "",
    repoPath: expandHome(rawProject.repoPath || ""),
    repoUrl: rawProject.repoUrl || "",
    defaultBranch: rawProject.defaultBranch || defaults.defaultBranch || "main",
    validationCommands: rawProject.validationCommands || defaults.validationCommands || [],
    contextLinks: rawProject.contextLinks || [],
    standards: rawProject.standards || defaults.standards || [],
    safetyRules: rawProject.safetyRules || defaults.safetyRules || [],
    reviewPipeline: rawProject.reviewPipeline || defaults.reviewPipeline || [],
    reviewPolicy,
    trustLeadApprovals: trustLeadApprovalsEnabled({ ...rawProject, reviewPolicy }),
    integrationBranch: integrationBranchName({ ...rawProject, reviewPolicy }) || integrationBranchName(defaults),
  };
}
